# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='for_rent_by',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Management Company/Broker', 'Management Company/Broker'), ('Tenant', 'Tenant')], max_length=255),
        ),
    ]
