# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20160503_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_activated',
            new_name='has_dishwasher',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedroom_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='cooling',
            field=models.CharField(choices=[('none', 'None'), ('air_conditioning', 'Air conditioning'), ('central_ac', 'Central A/C')], default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.CharField(choices=[('fully', 'Fully furnished'), ('lightly', 'Lightly furnished'), ('none', 'Unfurnished')], default='--', max_length=7),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_garbage_disposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_cable_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_electricity_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_heat_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_internet_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_water_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry',
            field=models.CharField(choices=[('washer_dryer', 'Washer & Dryer'), ('washer', 'Washer'), ('dryer', 'Dryer')], default='--', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry_type',
            field=models.CharField(choices=[('none', 'None'), ('in_unit', 'In-unit'), ('shared', 'Shared')], default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='lease_whole_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_in_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_space_count',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('3+', '3+')], default='--', max_length=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_type',
            field=models.CharField(choices=[('garage', 'Garage'), ('carport', 'Carport'), ('off_street', 'Off street'), ('other', 'Other')], default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='pet_allowed',
            field=models.CharField(choices=[('no', 'No pets allowed'), ('small', 'Small'), ('big', 'Big')], default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_title',
            field=models.CharField(default='title for your listing...', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('single_family_house', 'Single family house'), ('homestay', 'Homestay: live within house owner(share kitchen and/or bathroom)')], default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_floor',
            field=models.CharField(default='1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_sqft',
            field=models.CharField(default='square feet', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='additional_lease_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='for_rent_by',
            field=models.CharField(choices=[('owner', 'Owner'), ('management_company_broker', 'Management Company/Broker'), ('tenant', 'Tenant')], default='--', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_duration',
            field=models.CharField(choices=[('1year', '1 Year'), ('6months', '6 Months'), ('1month', '1 Month'), ('temp', 'Sublet/Temporary'), ('other', 'Other(Please explain)')], default='--', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_monthly_cost',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(max_length=9),
        ),
    ]
