# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20160519_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='furnished',
            field=models.CharField(choices=[('none', 'Unfurnished'), ('lightly', 'Lightly furnished'), ('fully', 'Fully furnished')], default='--', max_length=7),
        ),
        migrations.AlterField(
            model_name='listing',
            name='laundry',
            field=models.CharField(choices=[('none', 'None'), ('washer_dryer', 'Washer & Dryer'), ('washer', 'Washer'), ('dryer', 'Dryer')], default='--', max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unit_floor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
