# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20160519_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unit_sqft',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
