# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20160519_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='additional_lease_terms',
            field=models.TextField(blank=True, default='', help_text='Example: Owner pays for trash and sewer. Tenant responsible for gas and electric. Must have a minimum credit score of 640. Owner shovel snow, lawn, garden, driveway maintenance'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroom_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cooling',
            field=models.CharField(choices=[('none', 'None'), ('air_conditioning', 'Air conditioning'), ('central_ac', 'Central A/C')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='for_rent_by',
            field=models.CharField(choices=[('owner', 'Owner'), ('management_company_or_broker', 'Management Company/Broker'), ('tenant', 'Tenant')], max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnished',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('lightly_furnished', 'Lightly furnished'), ('fully_furnished', 'Fully furnished')], max_length=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnished_details',
            field=models.TextField(blank=True, default='', help_text='Example: bed only...'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='laundry',
            field=models.CharField(choices=[('none', 'None'), ('washer_and_dryer', 'Washer & Dryer'), ('washer', 'Washer'), ('dryer', 'Dryer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='laundry_type',
            field=models.CharField(choices=[('none', 'None'), ('in_unit', 'In-unit'), ('shared', 'Shared')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_deposit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_duration',
            field=models.CharField(choices=[('1_year', '1 Year'), ('6_months', '6 Months'), ('1_month', '1 Month'), ('sublet_temp', 'Sublet/Temporary'), ('other', 'Other(Please explain)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_duration_custom',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_monthly_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking_space_count',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3_plus', '3+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking_type',
            field=models.CharField(choices=[('garage', 'Garage'), ('carport', 'Carport'), ('off_street', 'Off street'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pet_allowed',
            field=models.CharField(choices=[('no_pets_allowd', 'No pets allowed'), ('small', 'Small'), ('big', 'Big')], max_length=14),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_description',
            field=models.TextField(blank=True, default='', help_text='Example: above hill, driveway slippery, renting to international student for long time...A student from China/Moroco in one of room'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_title',
            field=models.CharField(default='', help_text='Example: [home stay 1 bedroom][apartment with 3 room][in-law apartment]', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('single_family_house', 'Single family house'), ('homestay', 'Homestay: live within house owner(share kitchen and/or bathroom)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unit_floor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unit_sqft',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
