# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20161006_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unit_sqft',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
