# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20161006_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
