# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20161029_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-datetime_modified']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
