# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:37
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20161029_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinguser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartments'), ('house', 'Houses'), ('homestay', 'Homestay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unit_sqft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
