# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20161030_1753'),
        ('listings', '0011_auto_20161212_0337'),
    ]

    operations = [
    ]
