# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20161212_0337'),
        ('listings', '0011_auto_20161030_1753'),
    ]

    operations = [
    ]
