# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_merge_20161212_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinguser',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
