# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20161213_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='unit_sqft',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
