# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20161213_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='furnished_details',
            field=models.CharField(blank=True, default='', help_text='Furnishing detail, example: bed only...', max_length=512),
        ),
    ]
