# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20161214_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Image'),
        ),
    ]
