# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='0000000000', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=9)),
                ('for_rent_by', models.CharField(choices=[('owner', 'Owner'), ('management_company_or_broker', 'Management Company/Broker'), ('tenant', 'Tenant')], max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('lease_monthly_cost', models.PositiveSmallIntegerField()),
                ('lease_deposit', models.PositiveSmallIntegerField()),
                ('lease_duration', models.CharField(choices=[('1_year', '1 Year'), ('6_months', '6 Months'), ('1_month', '1 Month'), ('sublet_temp', 'Sublet/Temporary'), ('other', 'Other(Please explain)')], max_length=255)),
                ('lease_duration_custom', models.CharField(blank=True, default='', max_length=128)),
                ('date_available', models.DateField()),
                ('additional_lease_terms', models.TextField(blank=True, default='', help_text='Example: Owner pays for trash and sewer. Tenant responsible for gas and electric. Owner shovel snow, lawn, garden, driveway maintenance')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartments'), ('house', 'Houses'), ('homestay', 'Homestay')], max_length=20)),
                ('lease_whole_unit', models.BooleanField(default=False)),
                ('owner_in_building', models.BooleanField(default=False)),
                ('bedroom_count', models.PositiveSmallIntegerField()),
                ('bathroom_count', models.PositiveSmallIntegerField()),
                ('unit_sqft', models.PositiveSmallIntegerField(default=0)),
                ('unit_floor', models.PositiveSmallIntegerField()),
                ('furnished', models.CharField(choices=[('none', 'Unfurnished'), ('lightly_furnished', 'Lightly furnished'), ('fully_furnished', 'Fully furnished')], max_length=17)),
                ('furnished_details', models.CharField(blank=True, default='', help_text='Furnishing detail, example: bed only...', max_length=512)),
                ('is_water_included', models.BooleanField(default=False)),
                ('is_electricity_included', models.BooleanField(default=False)),
                ('is_heat_included', models.BooleanField(default=False)),
                ('is_internet_included', models.BooleanField(default=False)),
                ('is_cable_included', models.BooleanField(default=False)),
                ('parking_space_count', models.CharField(choices=[('0', 'None'), ('1', '1'), ('2', '2'), ('3_plus', '3+')], max_length=2)),
                ('parking_type', models.CharField(choices=[('garage', 'Garage'), ('carport', 'Carport'), ('off_street', 'Off street'), ('other', 'Other')], max_length=10)),
                ('pet_allowed', models.CharField(choices=[('no_pets_allowd', 'No pets allowed'), ('small', 'Small'), ('big', 'Big')], max_length=14)),
                ('laundry_type', models.CharField(choices=[('none', 'None'), ('in_unit', 'In-unit'), ('shared', 'Shared')], max_length=10)),
                ('property_title', models.CharField(default='', help_text='Example: [home stay 1 bedroom][apartment with 3 room][in-law apartment]', max_length=255)),
                ('property_description', models.TextField(blank=True, default='', help_text='Example: above hill, driveway slippery, renting to international student for long time...A student from China/Moroco in one of room')),
                ('has_dishwasher', models.BooleanField(default=False)),
                ('has_garbage_disposal', models.BooleanField(default=False)),
                ('has_microwave', models.BooleanField(default=False)),
                ('has_fridge', models.BooleanField(default=False)),
                ('cooling', models.CharField(choices=[('none', 'None'), ('air_conditioning', 'Air conditioning'), ('central_ac', 'Central A/C')], max_length=20)),
                ('image1', models.ImageField(blank=True, upload_to='images', verbose_name='Image')),
                ('image2', models.ImageField(blank=True, upload_to='images', verbose_name='Image')),
                ('image3', models.ImageField(blank=True, upload_to='images', verbose_name='Image')),
                ('listing_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.HousingUser')),
            ],
            options={
                'ordering': ['-datetime_modified'],
            },
        ),
    ]
